spring.application.name=ai-test-exercise

server.port=8081
spring.datasource.url=jdbc:h2:mem:testdb
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.security.user.name=user
spring.security.user.password=password

app.sale-enabled=false
