-- H2 schema (for Spring Boot schema.sql)

-- product_category
CREATE TABLE IF NOT EXISTS product_category
(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_uuid UUID NOT NULL DEFAULT RANDOM_UUID(),
    name VARCHAR(20),
    CONSTRAINT product_category_pkey PRIMARY KEY (id),
    CONSTRAINT uq_product_category_uuid UNIQUE (category_uuid)
);

-- product
CREATE TABLE IF NOT EXISTS product
(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_uuid UUID NOT NULL DEFAULT RANDOM_UUID(),
    name VARCHAR(30),
    price INT,
    category_id INT,
    CONSTRAINT product_pkey PRIMARY KEY (id),
    CONSTRAINT uq_product_uuid UNIQUE (product_uuid),
    CONSTRAINT fk_product__category FOREIGN KEY (category_id)
        REFERENCES product_category (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS idx_product__category_id
    ON product (category_id);

-- product_stock
CREATE TABLE IF NOT EXISTS product_stock
(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    stock_uuid UUID NOT NULL DEFAULT RANDOM_UUID(),
    stock INT,
    product_id INT,
    CONSTRAINT product_stock_pkey PRIMARY KEY (id),
    CONSTRAINT uq_product_stock_uuid UNIQUE (stock_uuid),
    CONSTRAINT fk_product_stock__product FOREIGN KEY (product_id)
        REFERENCES product (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS idx_product_stock__product_id
    ON product_stock (product_id);

-- sale (セール価格設定)
CREATE TABLE IF NOT EXISTS sale
(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sale_uuid UUID NOT NULL DEFAULT RANDOM_UUID(),
    sale_price INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    product_id INT NOT NULL,
    CONSTRAINT sale_pkey PRIMARY KEY (id),
    CONSTRAINT uq_sale_uuid UNIQUE (sale_uuid),
    CONSTRAINT fk_sale__product FOREIGN KEY (product_id)
        REFERENCES product (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS idx_sale__product_id
    ON sale (product_id);